### ISSUE TITLE
Redirect view to registration form

### ISSUE THREAD

**Issue by mbourqui** [jhuapl-boss/django-oidc#10]
Since the URL to the registration form is not trivial, it would be nice to have a view that build the redirection URL to the registration form.

On my site, it looks something like:
`https://mykeycloakserver.com/auth/realms/my-realm/protocol/openid-connect/registrations?client_id=MyClientId&redirect_uri=https%3A%2F%2Fmysite.com%2Fopenid%2Fcallback%2Flogin%2F&response_type=code`

**Comment by derek-pryor** [comment]
Since this plugin is a generic OpenID Connect plugin and not specific to Keycloak this will not be implemented. The reason is that there is nothing in the OpenID Connect specification for constructing a user registration URL.

If you want to allow user's to register themselves in Keycloak you can enable the "User registration" feature in the Keycloak realm. This will put a link to the registration form on the Keycloak login page.
